title: CSIRT Foundry 
description: "Custom tool development for security and incident response teams"
theme: tile5
permalink: /:categories/:title
root: /

pygments: true

authors:
    ChrisHorsley:
        name: Chris Horsley 
        mailhash: da01dadd2436ebbc1041d06b095fa899 
