title: CSIRT Foundry 
description: "Custom tool development for security and incident response teams"
theme: tile5
permalink: /:categories/:title
root: /

pygments: true

authors:
    ChrisHorsley:
        name: Chris Horsley 
        mailhash: ed265adf145a12d2e5f09b2a761f232f
